[all_servers]
dev_node ansible_host=34.201.209.35 ansible_user=centos ansible_password=DevOps321
stage_node ansible_host=44.195.25.170 ansible_user=centos ansible_password=DevOps321
prod_node ansible_host=13.220.34.247 ansible_user=centos ansible_password=DevOps321