- hosts: all_servers
  become: true
  tasks:
    - name: Install Docker Repository
      get_url:
        url: https://download.docker.com/linux/centos/docker-ce.repo
        dest: /etc/yum.repos.d/docker-ce.repo

    - name: Install Docker Engine on CentOS
      dnf:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present
        nobest: true

    - name: Start and Enable Docker Service
      service:
        name: docker
        state: started
        enabled: yes
